#!/bin/sh

options="Qtile\nPicom\ni3\nVim\nPolybar\nKitty\nAlacritty\nDunst"

chosen=$(echo -e $options | rofi -dmenu -p 'Config File' -i)
term="kitty"
launch="$term -e nvim $HOME/.config"

case $chosen in 
    Qtile)
        $launch/qtile/config.py
    ;;
    Picom)
        $launch/picom.conf
    ;;
    i3)
        $launch/i3/config
    ;;
    Vim)
        $launch/nvim/init.vim
    ;;
    Polybar)
        $launch/polybar/config
    ;;
    $term)
        $launch/$term/$term.conf
    ;;
    Alacritty)
        $launch/alacritty/alacritty.yml
    ;;
    Dunst)
        $launch/dunst/dunstrc
    ;;

esac
