#!/bin/fish

set options 'Qtile\nPicom\ni3\nVim\nPolybar\nKitty\nAlacritty\nDunst'

set chosen (echo -e $options | rofi -dmenu -p 'Config File' -i)

set term 'kitty'
set launch $term -e nvim $HOME/.config

switch $chosen
    case Qtile
        $launch/qtile/config.py
    case Picom
        $launch/picom.conf
    case i3
        $launch/i3/config
    case Vim
        $lauch/nvim/init.vim
    case Polybar
        $lauch/polybar/config
    case $term
        $lauch/$term/$term.conf
    case Alacritty
        $lauch/alacritty/alacritty.yml
    case Dunst
        $lauch/dunst/dunstrc
end
