#!/bin/fish
#
set uptime (uptime -p | sed 's/up //g')

# Options
set logout "Logout\x00icon\x1fsystem-log-out"
set suspend "Suspend\x00icon\x1fsystem-suspend"
set reboot "Reboot\x00icon\x1fsystem-reboot"
set lock "Lock\x00icon\x1fsystem-lock-screen"
set shutdown "Shutdown\x00icon\x1fsystem-shutdown"

# Rofi Choices
set options $lock\n$logout\n$suspend\n$shutdown\n$reboot

set chosen (echo -e $options | rofi -dmenu -p $uptime -theme $HOME/.config/rofi/themes/powermenu.rasi -i)

switch $chosen
    case Logout
        if test "$DESKTOP_SESSION" = "i3"
            i3-msg exit
        else if test "$DESKTOP_SESSION" = "qtile"
            qtile cmd-obj -o cmd -f shutdown
        end
    case Suspend
        systemctl suspend
    case Reboot
        reboot
    case Shutdown
        shutdown now
    case Lock
        betterlockscreen -l
end

