font_family      Fira Code Regular Nerd Font Complete Mono
bold_font        Hack Bold
italic_font      Hack Italic
bold_italic_font Hack Bold Italic

font_size 11.0

cursor #3cb754
cursor_text_color #2e3440

window_border_width 0
background_opacity 0.87

foreground #d8dee9
background #2e3440

color0 #3b4252
color8 #373e4d

#: black

color1 #bf616a
color9 #94545d 

#: red

color2  #a3be8c
color10 #809575 

#: green

color3  #ebcb8b
color11 #b29e75

#: yellow

color4  #81a1c1
color12 #68809a

#: blue

color5  #b48ead
color13 #8c738c 

#: magenta

color6  #88c0d0
color14 #6d96a5 

#: cyan

color7  #e5e9f0
color15 #aeb3bb

#: white
