require("plugins.treesitter")
require("plugins.telescope")
require("plugins.indent_guides")
require("plugins.comments")
-- require("plugins.bufferline")
require("plugins.harpoon_buffer")
require("plugins.colorizer")
require("plugins.git")
require("plugins.lualine")
require("plugins.nvim-surround")
require("plugins.nvim_autopairs")
require("plugins.nvim_tree")
require("plugins.react-extract")
